Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/xiongshihao/anaconda3/envs/test/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/home/xiongshihao/code/zzz/udp/works/server.py", line 56, in run
    msg_receiver(self.rec_queue,self.p_drop)
  File "/home/xiongshihao/code/zzz/udp/works/server.py", line 25, in msg_receiver
    msg,addr=rec_socket.recvfrom(1024)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: timed out
ACK TIMEOUT CLOSE
